[project]
name = "voidbound-platform"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
]
[tool.fastapi]
entrypoint = "voidbound_platform.main:app"

[dependency-groups]
dev = [
    "httpx2>=2.12.0",
    "pytest>=9.1.1",
]
[build-system]
requires = ["uv_build>=0.12.9,<0.13"]
build-backend = "uv_build"
